### ISSUE TITLE
Add support for PowerView blinds

### ISSUE THREAD

**Issue by exPHAT** [ExPHAT/node-hunterdouglas#2]
Originally from: https://github.com/ExPHAT/homebridge-hunterdouglas/issues/1#issuecomment-281355489

PowerView API documentation: https://cdn.hunterdouglas.com/static/product-operating-system-downloads/PowerView_Hub_Serial_API_1.pdf

**Comment by simurf** [comment]
Is there anything I can do to help get PowerView blinds implemented.
Would really love to get them added to my Homebridge setup.
Happy to do any testing required. Not much use beyond that except for hacking pieces togther and cutting and pasting.

**Comment by exPHAT** [comment]
@GooeyLizard9000 Actually, yeah. I don't own powerview blinds myself so its a real pain to test. I may try to whip something up and need someone to actually tell me it works. Are you on the homebridge slack?

**Comment by GvnCampbell** [comment]
Let me know if you need testing too. I was able to integrate mine using the ifttt plugin to execute scenes but would rather skip a 3rd party service and go direct.

**Comment by exPHAT** [comment]
@GvnCampbell Are you in the homebridge slack? May be easier to ask questions and thing over there

**Comment by simurf** [comment]
@exPHAT - yes I am on homebridge slack. Haven't used it in ages, but am on there.
Let me know what I can do.

**Comment by GvnCampbell** [comment]
@exPHAT. Just jumped on slack. Let me know if you need me to try anything. My user name is 'gavincampbell' over there.

**Comment by samwelnella** [comment]
I could also help with testing if needed.

**Comment by mteper** [comment]
Any luck getting it to work?

**Comment by exPHAT** [comment]
@mteper I haven't added support to this repo, but @GvnCampbell created his own homebridge plugin (https://github.com/GvnCampbell/homebridge-powerview)
